services:
  app:
    build:
      context: ./flenski
      dockerfile: Dockerfile
    container_name: flenski-frontend
    ports:
      - "5173:5173"
      - "5174:5174"
    volumes:
      - ./flenski:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - flenski-network
    command: ["sh", "-c", "chown node:node /app/install.sh && ./install.sh && tail -f /dev/null"]

networks:
  flenski-network:
    driver: bridge