services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  node:
    build:
      context: ./scripts
      dockerfile: ./scripts/Dockerfile
    container_name: node
    working_dir: /app
    volumes:
      - ./scripts:/app
      - ./data/scraped/ratsversammlung:/app/scraper/ratsversammlung/results/ratsversammlung/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "tail -f /dev/null"

  java:
    image: eclipse-temurin:21-jdk
    container_name: flenski
    working_dir: /app
    volumes:
      - ./backend/target/backend-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./data:/app/data
      - ./backend/.env:/app/.env
      - ./logs:/apps/logs
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_USE_TLS=${QDRANT_USE_TLS}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - BACKEND_API_KEY=${BACKEND_API_KEY}
    command: ["java", "-jar", "/app/app.jar"]

volumes:
  postgres_data:
