services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./data/qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  backend-base: &backend-base
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./logs:/app/logs
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - QDRANT_USE_TLS=${QDRANT_USE_TLS}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - VOCABULARY_FILE_PATH=${VOCABULARY_FILE_PATH}
    command: ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]

  backend:
    <<: *backend-base
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
    #command: ["sh", "-c", "tail -f /dev/null"]

  run-dev:
    <<: *backend-base
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./backend/.env:/app/.env
      - ./logs:/app/logs
    command: ["./mvnw", "spring-boot:run"]

  node:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: node
    working_dir: /app
    volumes:
      - ./scripts:/app
      - ./data/scraped/ratsversammlung:/app/scraper/ratsversammlung/results/ratsversammlung/
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "tail -f /dev/null"

volumes:
  postgres_data:
